### ISSUE TITLE
Outdated URL for SICP companion website

### ISSUE THREAD

**Issue by ackalker** [webframp/sicp-info#2]
The URL for the SICP companion website as mentioned in the Preface: http://www-mitpress.mit.edu/sicp/ is not reachable and appears to be outdated. The site is now reachable at: https://mitpress.mit.edu/sicp/

I understand that you may desire to keep the text as close to the original, but for readers wanting to access the supplementary material, the new URL could be very useful.

**Comment by webframp** [comment]
PR for his would be accepted I think

**Comment by webframp** [comment]
fixed in #5

**Comment by ackalker** [comment]
Thanks :)
